### PR TITLE
Fixed OSS CI for NNCF project

### PR DESCRIPTION
**Pull request by ljaljushkin**

### CODE REVIEW

**Comment by ljaljushkin** [comment]
Jenkins please retry a build

**Comment by izvekovvadimintel** [comment]
Jenkins please retry a build

**Comment by izvekovvadimintel** [comment]
Jenkins please retry a build

**Comment by ljaljushkin** [comment]
Jenkins please retry a build

**Comment by izvekovvadimintel** [comment]
Jenkins please retry a build

**Comment by izvekovvadimintel** [comment]
Jenkins please retry a build

**Comment by izvekovvadimintel** [comment]
Jenkins please retry a build

**Comment by izvekovvadimintel** [comment]
Jenkins please retry a build

**Comment by izvekovvadimintel** [comment]
Jenkins please retry a build

**Comment by izvekovvadimintel** [comment]
Jenkins please retry a build

**Comment by izvekovvadimintel** [comment]
Jenkins please retry a build

**Comment by izvekovvadimintel** [comment]
Jenkins please retry a build

**Comment by izvekovvadimintel** [comment]
Jenkins please retry a build

**Comment by ljaljushkin** [comment]
@AlexKoff88 @vshampor please review

**Pull request merged**
