### PR TITLE
assign specific version for networkx

### PR DESCRIPTION
**Pull request by FengYen-Chang**
Assign a specific version for networkx to avoid below error.

```sh
AttributeError: module 'networkx' has no attribute 'weakly_connected_component_subgraphs'
```
> Since the networkx 2.4 removed weakly_connected_component_subgraphs

### CODE REVIEW

**Comment by AlexanderDokuchaev** [comment]
Jenkins please retry a build

**Comment by izvekovvadimintel** [comment]
Jenkins please retry a build

**Comment by izvekovvadimintel** [comment]
Jenkins please retry a build

**Comment by AlexanderDokuchaev** [comment]
@AlexKoff88  Is it need to you?

**Comment by ljaljushkin** [comment]
@FengYen-Chang, this error should be fixed in #164. 
[`weakly_connected_components` is used](https://github.com/opencv/openvino_training_extensions/pull/164/files#diff-c8db294d242b2b130cada3c1bea8a604R208) instead of deprecated `weakly_connected_component_subgraphs`:


please check it with latest develop and close this PR if it works for you.

**Comment by FengYen-Chang** [comment]
@ljaljushkin Yes, it was fixed. Thanks.

**Pull request closed without merging**
